defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: TheShey的个人博客

title: TheShey的个人博客
description: 个人主页
url: "http://TheShey.github.io"

author:
  name: TheShey
  email: shilishihe@gmail.com
  github: TheShey
  bio: keep calm and carry on!

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

markdown: kramdown